stages:
  - cache dependencies
  - test
  - build

include:
  - template: Code-Quality.gitlab-ci.yml

.python:
  image: python:3.8-buster
  stage: test
  variables:
    PIPENV_VENV_IN_PROJECT: enabled
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install pipenv==2020.11.15
    - pipenv install --dev --deploy
    - export PATH="$CI_PROJECT_DIR/.venv/bin:$PATH"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/
      - .cache/pip
      - .pytype
      - .mypy_cache
      - .pytest_cache

cache-dependencies:
  extends: .python
  stage: cache dependencies
  script:
    - echo "Dependencies cached"

black: 
  extends: .python
  script: 
    - make black-check

flake8: 
  extends: .python
  script: 
    - make flake8

bandit: 
  extends: .python
  script: 
    - make bandit

isort: 
  extends: .python
  script: 
    - make isort-check

safety: 
  extends: .python
  script: 
    - make safety

mypy: 
  extends: .python
  script: 
    - make mypy

# need to fix this
# pytype: 
#   extends: .python
#   script: 
#     - make pytype

tests: 
  extends: .python
  script: 
    - make tests
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      cobertura: coverage.xml

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

.build-docker:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    CI_REGISTRY_IMAGE: registry.gitlab.com/guillaumedsde/dht-torznab
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-build-master:
  extends: .build-docker
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/api" . -f docker/Dockerfile --target api
    - docker build --pull -t "$CI_REGISTRY_IMAGE/listener" . -f docker/Dockerfile --target listener
    - docker push "$CI_REGISTRY_IMAGE/api"
    - docker push "$CI_REGISTRY_IMAGE/listener"
  only:
    - master

docker-build:
  extends: .build-docker
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_SLUG" . -f docker/Dockerfile --target api
    - docker build --pull -t "$CI_REGISTRY_IMAGE/listener:$CI_COMMIT_REF_SLUG" . -f docker/Dockerfile --target listener
    - docker push "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE/listener:$CI_COMMIT_REF_SLUG"
  except:
    - master
