
stages:
  - build
  - analyse

.python:
  image: python:3.8-buster
  stage: analyse
  variables:
    PIPENV_VENV_IN_PROJECT: enabled
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install --no-cache-dir pipenv==2020.11.15
    - pipenv install --dev --deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/
      - .cache/pip
      - .pytype
      - .mypy_cache

cache-dependencies:
  extends: .python
  stage: build
  script:
    - echo "Dependencies cached"



black: 
  extends: .python
  script: 
    - make black-check

flake8: 
  extends: .python
  script: 
    - make flake8

bandit: 
  extends: .python
  script: 
    - make bandit

isort: 
  extends: .python
  script: 
    - make isort-check

safety: 
  extends: .python
  script: 
    - make safety

mypy: 
  extends: .python
  script: 
    - make mypy

pytype: 
  extends: .python-check
  script: 
    - make pytype
