services:
  magneticod:
    build:
      context: https://github.com/boramalper/magnetico.git#master
      dockerfile: Dockerfile.magneticod
    depends_on:
      - beanstalkd
    command:
      - --database=beanstalkd://beanstalkd:11300/magneticod_tube
      - --verbose
      - --leech-max-n=500
      - --indexer-interval=1
      - --indexer-max-neighbors=10000

  beanstalkd:
    image: guillaumedsde/beanstalkd-distroless:1.12
    command:
      - -b
      - /data
      - -V
      - -f
      - "2400000"
      - -z
      - "1048560"
    volumes:
      - beanstalkd-binlog:/data
    ports:
      - 127.0.0.1:11300:11300

  postgres:
    image: postgres:15-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: torznab
      POSTGRES_PASSWORD: torznab
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  beanstalkd-binlog:
