"""Initial Migrations

Revision ID: a12e8d5a1107
Revises: 
Create Date: 2023-06-03 11:00:51.898046

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a12e8d5a1107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('info_hash', sa.LargeBinary(), nullable=False),
    sa.Column('occurence_count', sa.Integer(), nullable=False),
    sa.Column('peer_count', sa.Integer(), nullable=True),
    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_hash', name='unique_info_hash'),
    schema='dht_torznab'
    )
    op.create_index('idx_torrent_name_tsv', 'torrents', ['search_vector'], unique=False, schema='dht_torznab', postgresql_using='gin')
    op.create_table('files',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['dht_torznab.torrents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dht_torznab'
    )
    op.create_index(op.f('ix_dht_torznab_files_torrent_id'), 'files', ['torrent_id'], unique=False, schema='dht_torznab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dht_torznab_files_torrent_id'), table_name='files', schema='dht_torznab')
    op.drop_table('files', schema='dht_torznab')
    op.drop_index('idx_torrent_name_tsv', table_name='torrents', schema='dht_torznab', postgresql_using='gin')
    op.drop_table('torrents', schema='dht_torznab')
    # ### end Alembic commands ###
