name: Github Action Continuous Integration (CI) pipeline
on:
  - push

jobs:
  python-code-checks:
    strategy:
      fail-fast: false
      matrix:
        include:
          - check-name: ruff
            check-command: ruff check --format github .
          - check-name: black
            check-command: black .
          - check-name: mypy
            check-command: mypy .
    name: ${{ matrix.check-name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pip install poetry==1.5.0
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: 'poetry'
      - run: ${{ matrix.check-command }}